AWSTemplateFormatVersion: '2010-09-09'
Resources:
  TestBucket123:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: testbuck7152932
  askdjhaskjdho:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: testbuck8162938691
